### ISSUE TITLE
Build command for Desktop is wrong

### ISSUE THREAD

**Issue by SuperNerd-James** [BAndysc/AvaloniaVisualBasic6#10]
If you clone the repository (via ZIP), and enter it, the given build string for Desktop does not work. I had to edit it to:

"dotnet build AvaloniaVisualBasic.Desktop/AvaloniaVisualBasic.Desktop.csproj"

then it compiled.

**Comment by BAndysc** [comment]
Right, fixed the typo, thanks for reporting!
