### ISSUE TITLE
Can this toy be compiled VB6 code?

### ISSUE THREAD

**Issue by zyyujq** [BAndysc/AvaloniaVisualBasic6#11]
Can this toy be compiled VB6 code

**Comment by BAndysc** [comment]
Are you asking if this project can compile VB6 code? The answer is: currently no, **BUT** **it can run VB6 code** via built in interpreter. This is slower than native code compilation, but other than that it does run VB6 code. However, currently it doesn't support all VB6 syntax. More syntax and features might be added in the future. Does it answer you question?
