### ISSUE TITLE
Antlr4 build task requirements

### ISSUE THREAD

**Issue by phillijw** [BAndysc/AvaloniaVisualBasic6#2]
```
1>Antlr4BuildTasks.targets(138,9): Error ANT02 : Cannot find Java executable''   at Antlr4.Build.Tasks.RunAntlrTool.SetupJava()
   at Antlr4.Build.Tasks.RunAntlrTool.Execute()
1>Antlr4BuildTasks.targets(138,9): Error ANT02 : The Antlr4 tool failed.
1>Antlr4BuildTasks.targets(138,9): Error ANT02 : Cannot find Java executable''   at Antlr4.Build.Tasks.RunAntlrTool.SetupJava()
   at Antlr4.Build.Tasks.RunAntlrTool.Execute()
1>Antlr4BuildTasks.targets(138,9): Error ANT02 : The Antlr4 tool failed.
```

Might be good to have some basic instructions for dependencies required or else automatically install these dependencies using nuget?

**Comment by phillijw** [comment]
I do see there's `meta/build_cloudflare.sh` but even it doesn't suggest java is a requirement

**Comment by BAndysc** [comment]
What OS are you using? What IDE/command line did you use? [Antlr4BuildTasks](https://github.com/kaby76/Antlr4BuildTasks?tab=readme-ov-file#new-approach) is able to download java runtime on its own and there should be nothing required other than `dotnet run`. I am afraid in this case it might be some Antlr4BuildTasks corner case.

**Comment by phillijw** [comment]
I'm on macos using jetbrains rider. I'll try some more things tomorrow via commandline

**Comment by BAndysc** [comment]
Looks like Antlr4BuildTasks doesn't support ARM macs: https://github.com/kaby76/Antlr4BuildTasks/blob/master/Antlr4BuildTasks/Tasks/RunAntlrTool.cs#L937-L946

I also use one, but apparently I have java installed. So I guess you have to install it manually as well. I will update the readme later.

**Comment by davidbitterlich** [comment]
Manually installing Java did not work for me on macOS. I needed to adjust the csproj file to add <JavaExec> to it (according with the correct path).

Maybe this would be good to be added to the readme in case compilation does not work?
