### ISSUE TITLE
Freeze on selection of RoundedSquare

### ISSUE THREAD

**Issue by GooRoo** [BAndysc/AvaloniaVisualBasic6#4]
**Steps to reproduce:**
1. Add a Shape to the form.
2. Try changing its `Shape` property to `5 - RoundedSquare`.

**Expected result:**
The property is changed successfully.

**Actual result:**
Almost everything hangs and doesn't react to input event.

https://github.com/user-attachments/assets/7f455f1a-a489-4a07-9003-892d64a2d530

**Partial recovery:**
It's possible to close the form design window. Then a message box appears. After reopening the form, you can observe the absence of the added shape (and probably of the rest of unsaved changes)

**Comment by BAndysc** [comment]
Nice catch! Fixed, thanks
