### ISSUE TITLE
Proposal: use pixelated font version

### ISSUE THREAD

**Issue by x1unix** [BAndysc/AvaloniaVisualBasic6#5]
There is a [pixelated](https://github.com/jdan/98.css/tree/main/fonts/converted) version of MS Sans Serif font used in [98.css](https://jdan.github.io/98.css/) CSS framework.

<img width="763" alt="image" src="https://github.com/user-attachments/assets/d1f097a3-f827-4f5a-9320-3b3d62e51b06">

Adopting this font would significantly increase nostalgia vibes.

**Comment by BAndysc** [comment]
That's a good idea! Changed the font now, thanks for the proposal
