### ISSUE TITLE
Excuse me, which ide directory should I put after I compiled AvaloniaVisual Basic.Standalone?

### ISSUE THREAD

**Issue by woeoio** [BAndysc/AvaloniaVisualBasic6#6]
Excuse me, which ide directory should I put after I compiled AvaloniaVisual Basic.Standalone? I only found the ide directory under the source code

![dbcaf1b0-92ff-4cf7-a715-9dd9589f808d](https://github.com/user-attachments/assets/8487b1ef-6615-4eba-bb15-eacdc273333d)

![f99cdf17-26ec-4e6a-b233-e6b125267520](https://github.com/user-attachments/assets/71c3a4fc-6af4-437b-867e-546c402f59c1)

**Comment by woeoio** [comment]
![f57284a5-a07b-460d-9cb4-8912f3abe760](https://github.com/user-attachments/assets/b872320d-6ba7-43f7-99f7-209884afab5d)

**Comment by BAndysc** [comment]
Hey, the readme was very confusing indeed, updated it, it is now just two commands:

```
dotnet publish AvaloniaVisualBasic.Desktop -f net9.0 -o bin/
dotnet publish AvaloniaVisualBasic.Standalone -f net9.0 -o bin/standalone/
```

**Comment by woeoio** [comment]
> Hey, the readme was very confusing indeed, updated it, it is now just two commands:
> 
> ```
> dotnet publish AvaloniaVisualBasic.Desktop -f net9.0 -o bin/
> dotnet publish AvaloniaVisualBasic.Standalone -f net9.0 -o bin/standalone/
> ```
> 
> Now you can run `./bin/AvaloniaVisualBasic.Desktop` and "make project" should work

thank you, really working !
