### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by everythingability** [BAndysc/AvaloniaVisualBasic6#8]
Now do HyperCard :-)

**Comment by BAndysc** [comment]
It's tempting, but unlike VB6 I didn't grow up with this software, so I don't really know, big part of a project like this is nostalgia, so I am afraid this is unlikely to happen. For now I will close the issue, but if anyone ever recreates it, feel free to share it here!

**Comment by everythingability** [comment]
Cheers, my request is nostalgia-based too... a couple of closest are Decker and Cardstock (Python-based).  Thing is, I want want the olden days without the rickets.
